name: tripmate
description: "TripMate – Cross Platform Travel Planner Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  http: ^1.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image_picker: ^1.0.4
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assests/images/bali.jpeg
    - assests/images/dubai.jpg
    - assests/images/italy.jpg
    - assests/images/maldives.jpg
    - assests/images/france.jpg
    - assests/images/germany.jpg
    - assests/images/singapore.jpg
    - assests/images/vitenam.jpg
    - assests/images/malaysia.jpg
    - assests/images/thailand.jpg
    - assests/images/search.jpg
    - assests/images/ai_icon.png
    - assests/images/tripmate_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assests/images/tripmate_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assests/images/tripmate_logo.png"